apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
- name: kyverno
  version: 3.0.5
  repo: https://kyverno.github.io/kyverno/
  valuesFile: values.yaml
  namespace: kyverno
  releaseName: kyverno

# Delete kyverno PDB, not useful on SNO
patches:
  - delete-pdb-patch.yaml