apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openid-client-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgAngaVv2SHO1hYm73OqxxgZMMlIfZJ2zb4v9EGtU3txoaXhw+EQ4PzJhyHET7S326po++cueYFnfa6j1q4T5dP6h5HP5z0+uTd/vEZJOo605ibH9wXm85AVcyo/i/v+InAnY2aZPaG8peoVOwDQlRyCnuZDWP8azHcwgc1zxpYsei+o5B/3viRx1tdTA3PyfA6lRzjcRwjrdDndjklvnTmS7pMnGlUMTfRSA4QtaFPXMOGxbVtxysqtpxDjrCMFAqY3/uVVto+mD3zgK2beqQlK7zFedvATkQSJQNXpLWs8+uKSMLoedhvgV4MQyoWhSPP76ZQV1PVmIMcJfYaVM5JyXZXnYlruBvp6m7SsVVAgiv0NHP4yTyTWo2OqcNs/kviWYRT+asT6toeeCMcNT+958S6d9DBHC/TD9jeXHHCF+LGAsIInWU41eCiqp8wPwXTzW0ATMJz5OgYrdziM7JdtA/7pBZurCrFT8Drjs59n9kwOmuWdmRO+jjR4VEGgvqyjemOz014dWg7q2Ilp6j1s9YZTYNoK96Jr15bbcSM0jRYZTaCAvtC40VPFin2U1b9mo11N2RGV7skOXdH+grOA1nEd+mGFPzQYzY5t89Bc4cVZt2Yz1cLg+FIT581IP3tieGXaaEDxHEkJqI/ZpYKIP7GWdCAtryaXaC9UxxUA4gCb2jyfPLx2LP2WNL4Q/f3bwli5s1TbwniMdUjTfVORXjeR0b3X1om1pr2bL9xBURymU9o=
  template:
    metadata:
      name: openid-client-secret
      namespace: openshift-config
    type: Opaque