apiVersion: remediation.medik8s.io/v1alpha1
kind: NodeHealthCheck
metadata:
  name: nodehealthcheck-sample
spec:
  minHealthy: 51% 
  maxUnhealthy: 29% 
  pauseRequests: []
  stormCooldownDuration: 60s 
  remediationTemplate: 
    apiVersion: self-node-remediation.medik8s.io/v1alpha1
    name: self-node-remediation-automatic-strategy-template
    namespace: openshift-workload-availability
    kind: SelfNodeRemediationTemplate
  escalatingRemediations: 
    - remediationTemplate:
        apiVersion: self-node-remediation.medik8s.io/v1alpha1
        name: self-node-remediation-automatic-strategy-template
        namespace: openshift-workload-availability
        kind: SelfNodeRemediationTemplate
      order: 1
      timeout: 300s
  selector: 
    matchExpressions:
      - key: virt
        operator: equal
        value: true
  unhealthyConditions: 
    - type: Ready
      status: "False"
      duration: 300s 
    - type: Ready
      status: Unknown
      duration: 300s 