apiVersion: v1
data:
  config: eyJ0bHNDbGllbnRDb25maWciOnsiaW5zZWN1cmUiOmZhbHNlfX0=
  name: aW4tY2x1c3Rlcg==
  namespaces: cHJvZHVjdC1jYXRhbG9nLWNpY2QscHJvZHVjdC1jYXRhbG9nLWRldixwcm9kdWN0LWNhdGFsb2ctZ2l0b3BzLHByb2R1Y3QtY2F0YWxvZy1tb25pdG9yLHByb2R1Y3QtY2F0YWxvZy1wcm9kLHByb2R1Y3QtY2F0YWxvZy10ZXN0
  server: aHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3Zj
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: cluster-kubernetes.default.svc-3396314289
type: Opaque
