apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  servingCerts:
    namedCertificates:
    - names:
      - api.home.ocplab.com
      servingCertificate:
        name: openshift-api-certificate