apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: signing-secrets
  namespace: openshift-pipelines
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: signing-secrets
  dataFrom:
  - extract:
      key: COSIGN
