apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-tools

bases:
# Nexus
- https://github.com/redhat-cop/gitops-catalog/nexus2/base
# Sonarqube
- https://github.com/redhat-cop/gitops-catalog/sonarqube8/overlays/plugins

resources:
- namespace.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: sonarqube:lts-community
  target:
    kind: Deployment
    name: sonarqube