kind: ConfigMap
apiVersion: v1
metadata:
  name: router-certs-default
  namespace: openshift-config
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFvzCCA6egAwIBAgIUWGS8RPHDyKpKfkAZr+L+aWsbi/AwDQYJKoZIhvcNAQEN
    BQAwbzELMAkGA1UEBhMCQ04xEDAOBgNVBAgMB0JlaWppbmcxEDAOBgNVBAcMB0Jl
    aWppbmcxEDAOBgNVBAoMB2V4YW1wbGUxETAPBgNVBAsMCFBlcnNvbmFsMRcwFQYD
    VQQDDA50ZXN0LmxhYi5sb2NhbDAeFw0yMjA3MDUxMDAyNTJaFw0zMjA3MDIxMDAy
    NTJaMG8xCzAJBgNVBAYTAkNOMRAwDgYDVQQIDAdCZWlqaW5nMRAwDgYDVQQHDAdC
    ZWlqaW5nMRAwDgYDVQQKDAdleGFtcGxlMREwDwYDVQQLDAhQZXJzb25hbDEXMBUG
    A1UEAwwOdGVzdC5sYWIubG9jYWwwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
    AoICAQDiiwSYfnxwvEVXH7wpF9Rx4pEmOXq0dDhU8jcsDy42JUXBr1gKOTj6+2Dy
    TV0+D/C4nCT8s8VPajm97GAR/DP77/WPW4IPDck0cH+VUcMVUgbTaeLPT+JdCSB4
    XhzJ1ija8ox4+zrGG1NNSZzzB8vmGICpBbvfJ0gz6cT6rIM7hBFBKSHmQOtyM8J4
    EgaBeHyKFCI9m2ngiasSJ2Ylw6FB84a+D73hWPH8i04uxd3j77pP2Ebixveghofh
    b/e6lp8CoueFAqKIPajGfkFh7+pVqs/MpR/H9FVwAvHuuW5QlFo7c9NgzLLUhwKo
    qeZDtSg0vtG0ks8MP28iZkdUKnJww/XT0KTygS63iRGTHkc02a1doeH5ThZ8TV2Q
    3ip88ytYctIK0jRMCzyhf5/aRa31QWrH8J9DY/Aa+lOlc/iOniq9WPnI2QDcV2Xe
    PJT3EM5lnejtt24yCSxrGdbrjxebBOwLmGR7LTrEiD99rCrOF5/ZXaruzBiBQj9p
    bRLQ6ovVyoxRyeLjjS+duSFVyC1nay08WVVp11xixDEd9KMPNXFS/cukmrvn5dor
    KkI6iepHG3+WSvdpq8YMNSvmmKGbCMzMi7u/kWnR7fbLdM0CxOcJtybIJoGPc/gS
    Qeziyjcr+XUaT9mOdEaZHWESz/C0ouMtPbvLpPEnTJTYmls/nwIDAQABo1MwUTAd
    BgNVHQ4EFgQUDRnGxy09KxuU0+qvpw1CdL8Xd8AwHwYDVR0jBBgwFoAUDRnGxy09
    KxuU0+qvpw1CdL8Xd8AwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQ0FAAOC
    AgEA4L8xueeiDWrGdbBKhzuG4sHHUEIs5uRaSm75YafEIZv3vPB0GbAFD5nPNX2m
    ppHRGr/EigIQfbbxrRIT8wQbzWOSCIjz4g/WhngVJdNtwy8aKX55gltDBRpmSCxH
    y+RVJS7FtYoZlJSQ6SEylaEl48PhUp5UImeb5nwCwIU7ojJNDrfCETo/5j2bW9iX
    f2QJ8HUnb/5/E6aY4czTiNL0+0GRSduiDPcWs81//2mw9yIGuzM3RC8MH9UezW4G
    bH3vctCldOCKEOUvwwe1kXTvxfSGjkTVb+90KU+UOgUA0MN4ExHFqlknzduaZk8X
    qvhYcC3W49lV9ca8S3Rk8XKeEALVwchwelihESsqi19j4DfM1Lno9hUgWV+dDTXy
    4T1dFsFRmD5Przmt1Di57PIsS82m1RpzLMg1xC4THDyR6NXxRWDD8ZOius8ktMxD
    QkeWCgepNiZZXpYcD42ZJqwGNwTezwtdJXV7WjQHx3uSnLeT7yh/DphOqPeyjGk9
    FrjxgFiLM6h+0VRdU/CPIUp2WiA/bj+PJVGxxEFviXWyHHAh4XoU2rrx9p+Bc9Qh
    fUo4vu7xj3o6jw5p3GOAzOS4DSkY8ldL+BoRMhmEnQp5KvHvv/rk4sBp2UXsmc/K
    56RRv6UZR/F7JMSxcNYCRoGLTY4/qYmr0iLUOG6JF93dZ1c=
    -----END CERTIFICATE-----