# commonAnnotations:
#   argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
- ../../../../../../components/apps/acs-operator/overlays/secured-cluster

patches:
  - patch: |-
      - op: replace
        path: /spec/clusterName
        value: home
    target:
      kind: SecuredCluster
      name: stackrox-secured-cluster-services
