# Assumes the cluster admin had pre-created the sealed-secrets project and secret.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: letsencrypt-job

bases:
- github.com/redhat-cop/gitops-catalog/letsencrypt-certs/base
resources:
- sealed-cloud-dns-credentials.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env
      value:
        - name: STAGING
          value: "false"
        - name: PATCH_API_SERVER
          value: "true"
  target:
    kind: Job
    name: letsencrypt-certificates-job