apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quay

resources:
- namespace.yaml
- github.com/redhat-cop/gitops-catalog/quay-registry-operator/operator/overlays/stable-3.6
