apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-pipeline-operator
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: components/apps/pipelines-operator/overlays/patch-config-parameters
    repoURL: https://github.com/gnunn-gitops/cluster-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false