apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-tools
  labels:
    gitops.ownedBy: dev-tools
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: dev-tools
  source:
    path: components/apps/dev-tools/overlays/default
    repoURL: https://github.com/gnunn-gitops/cluster-config.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true