apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: rhsso
  namespace: sso
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: sso
spec:
  instances: 1
  profile: RHSSO
  keycloakDeploymentSpec:
    experimental:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - bootp-73.69-235.rhts.eng.pek2.redhat.com
    imagePullPolicy: Always
  externalAccess:
    enabled: true
    #host: sso.${SUB_DOMAIN} 
    #bug: https://access.redhat.com/solutions/6365791