apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- prod-namespace.yaml

# Patch in namespace for Argo CD that is managing this namespace
patches:
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: product-catalog-prod
  target:
    kind: RoleBinding
    name: gitops-argocd-extended-rolebinding