apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '21'
  labels:
    gitops.ownedBy: cluster-config
  name: config-quay-registry-operator
spec:
  destination:
    namespace: quay
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: clusters/local.home/apps/quay-registry-operator/overlays/qnap
    repoURL: https://github.com/gnunn-gitops/cluster-config.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true