apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '3'
  labels:
    gitops.ownedBy: cluster-config
  name: config-cluster-certs
spec:
  destination:
    namespace: openshift-config
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: clusters/local.home/apps/cluster-certs/overlays/all
    repoURL: https://github.com/gnunn-gitops/cluster-config.git
    targetRevision: main