apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: google-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgAUgPS8TMHri7EIkamt8uxPDA0icQVDlwFVlIS0D4AO4SoES8UKSFKoMr2bpsFx7hoXayJamDTiF9EVLhOPTj8ClRXeLWF7N3rXPooJ5wU/JJrvTSaTa7cGPqCHFVvU4StaIvj03I9ll1qUXvm3rYwbaZz+1Qay39mSDdzQ4tvF2VtaL010NWypx2/UFPQVDXOla/Ik6J1uks5p3F5C0JCTJY75UGQjS0jfG4qmsgQXTuavQ7lUIHZGprna4pzbdPPYKQzIeJ1uGEq2blbFQAYcqDy1Zez0tMEk1xTtShr0by+Hb3WrWIDDYMUtVSAuuVzSxTy03eS7Ibi51jbGGY8Q4CTahiTYCoMslhjjpnTYR3AYVpVj1HJjvz72t7FmV375ox1fUIll/A7eYlJFIBEScrlw1hBd/xM/VYHaz9iQBxGXFq2PgjD32Gzl+ClRr94uFoLXiURUnuENF1WvyDOO8Du3WhwYp/XuWJTt1mE9SSUN6/JKwMyuwWlcE0+4tcsFOuubPzwnot2qgXFUZxC1sEANrHoAjMtiwv8aYIpjrhznrCgU14XX0gtzG6iNobhebCyi2uph51jpbS3MXH+ihIga4ZgcMnBsCfqirFib/cALS1OMXDX456/NWWCIzj/zAtwi3Cdw/ItQexkvaolAHYx0Uj3xsY2CqNoOZ7J1Z1/sF7UYtEdGUYPs0tDlZtZG0cJhNqjcN3mb/kpLZt1mvzfb4q6Rg0E=
  template:
    metadata:
      creationTimestamp: null
      name: google-secret
      namespace: openshift-config
    type: Opaque

