apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-certs
  namespace: vault
spec:
  secretName: vault-certs
  issuerRef:
    name: vault-service
    kind: ClusterIssuer
  dnsNames: 
  - vault.apps.hub.lab.local
  # Service Active FQDN
  - vault.vault.svc.cluster.local