apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: set-max-pods
spec:
  autoSizingReserved: true
  machineConfigPoolSelector:
    matchLabels:
      #pools.operator.machineconfiguration.openshift.io/master: ""
      machineconfiguration.openshift.io/role: "perf"
  kubeletConfig:
    podsPerCore: 10
    maxPods: 450
    kubeAPIBurst: 200
    kubeAPIQPS: 100
