apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '11'
  labels:
    gitops.ownedBy: cluster-config
  name: config-openshift-monitoring
spec:
  destination:
    namespace: openshift-monitoring
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: clusters/local.home/apps/openshift-monitoring/base
    repoURL: https://github.com/gnunn-gitops/cluster-config.git
    targetRevision: main