apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-camel-k-operator
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: components/apps/camel-k-operator/base
    repoURL: https://github.com/gnunn-gitops/cluster-config.git
    targetRevision: main
  syncPolicy:
    automated: {}