apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
  annotations:
    argocd.argoproj.io/sync-options: Validate=false,ServerSideApply=true, SkipDryRunOnMissingResource=true
spec:
  pipeline:
    enable-custom-tasks: true
    metrics.taskrun.level: taskrun
    metrics.pipelinerun.level: pipelinerun
    metrics.taskrun.duration-type: lastvalue
    metrics.pipelinerun.duration-type: lastvalue
