apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  argocd.argoproj.io/instance: openshift-gitops

resources:
- ../../base
- monitor-namespace.yaml
- monitor-operatorgroup.yaml

# Patch in namespace for Argo CD that is managing this namespace
patches:
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: product-catalog-monitor
  target:
    kind: ClusterRoleBinding
    name: gitops-argocd-extended-rolebinding

patchesJson6902:
- target:
    version: v1alpha1
    group: operators.coreos.com
    kind: Subscription
    name: grafana
  path: patch-grafana-channel.yaml
- target:
    version: v1alpha1
    group: integreatly.org
    kind: Grafana
    name: grafana
  path: patch-grafana-sar.yaml
- target:
    version: v1
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: cluster-monitoring-view
  path: patch-cluster-monitoring-view.yaml