apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps-product-catalog
  labels:
    argocd.argoproj.io/project-inherit: global
spec:
  description: Product Catalog Team Project
  destinations:
  - namespace: 'product-catalog-dev'
    server: 'https://kubernetes.default.svc'
  - namespace: 'product-catalog-test'
    server: 'https://kubernetes.default.svc'
  - namespace: 'product-catalog-prod'
    server: 'https://kubernetes.default.svc'
  - namespace: 'product-catalog-cicd'
    server: 'https://kubernetes.default.svc'
  - namespace: 'product-catalog-monitor'
    server: 'https://kubernetes.default.svc'
  - namespace: 'product-catalog-gitops'
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - '*'
  sourceNamespaces:
  - product-catalog-gitops