resources:
  - ../../base
  - htpass-secret.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/identityProviders/0
        value:
          htpasswd:
            fileData:
              name: htpass-secret
          mappingMethod: claim
          name: htpasswd
          type: HTPasswd
    target:
      group: config.openshift.io
      kind: OAuth
      name: cluster
      version: v1
