kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  name: gitops-argocd-extended-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitops-argocd-extended-role
subjects:
  - kind: ServiceAccount
    name: argocd-argocd-application-controller