apiVersion: batch/v1
kind: Job
metadata:
  name: init-quay
  annotations:
    # argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/ansible-automation-platform-21/platform-resource-runner-rhel8:2.1
          envFrom:
          - secretRef:
              name: init-user-password
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash

              echo "Waiting for two minutes for quay to be ready"

              sleep 120

              git clone https://github.com/gnunn-gitops/quay-init

              ansible-galaxy collection install -r collections/requirements.yml

              ansible-playbook quay-init.yaml -e quay_init_password=$quay_init_password
          name: init-quay
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 30