apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quay

resources:
- ../../../../../../components/apps/quay-registry-operator/overlays/default
- registry-config-bundle-secret.yaml