apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: registry
spec:
  components:
    - kind: objectstorage
      managed: false
    - managed: true
      kind: tls
    - managed: false
      kind: horizontalpodautoscaler
  configBundleSecret: config-bundle-secret