apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: config-bundle-secret
  namespace: quay
spec:
  encryptedData:
    config.yaml: AgC5TmNqb0fRCExfYaHR4sW0mrzyuVFHpTDYNPIhrkBODR4z8C6lkqIZO2EcXc3ahQc2YTt35e7WHrG+NKe5RrpvHowLC7fD/svF1frrOQREphXiY+WseXQonWMsdYHkeOx2F2mz0t/FCOx3hWJQFSNFbyI7i03K6yP2h3AhLYEOrBtE4B5BncWxtdZDdZH35xRjKO3J/e+oWTX9EQR2qVqTO3SKJBv9JLruBUZu9/yg4wQAdz+AoTZMdT+ntpxFpWPnJp3LqtnRxca8DpbgYSxE38NbdxwhtzPWrP/8bFTrcSz8f9z/LkX6MVqUq31B0YvghklfvuG992md4+RIlJrVBozJxDjBHAR5NsnxxEGYPa/+o8uWQRpurWL4IAfrt/xqDBUmBDT+71WOALVqwVFMyea1vlbU/58zuaFWnxwDblvJjGv3Iw0CBOtKKNpHtvIsak7PFRSdL+is/MY/qZsVt4gwdUiZDBBDkNnm1QyIDtWz3s0qFxF+rfnt15eXTc91rhaFAXAGqybMj0TblrhnHs3elNqTgp48HnOOiZetay5s5lFcx1MS4/lv0OTUCvhxEX1wNU/NZzyy5M1wfFvR17DSjvDCp1uAa+AwSWnaffuAk1JpRkN2TvcX5ksRHJTLfjlCnX+OC7Lz51BUJ7UZ0b9gs4UxFmBEGK8T0RX8c+8z05N5ZuqiIMSXmFEkb4Nrf1mntipeLvn+gvlwTrke1GyrsL7n4Kss2yD9uSo/WsGHc9KXQEDz3uTbDad3V592KhH4ttCl6FI+6NKwV8TqUADbSBCvHARtLaB6sZlekLf1O5vfT5HI0q13erfi9QbkMmRVUOJSdMKbD254HndyW0j4HtqomN3e/UE0F1ig16epClkFTRv7/uoTJOKHeEV+AzyAAdJOlBj9CHTd5spFmryQye3MHcDgSlmQ44ztMOf05hcmrtubjb18gqWCmroJKeNHFt2RtCv1T9VwA0BBW2baDWFdHtB6e1H/OGn479NWb2Vp3JQkipbCjBnIXE3yxGZUC9j0ZJs/A1YFRMvjVLW/gJZmVN9srfMFtZLfQiQ//mkKfGnf75AqZ6Ax0/+2jQQVmloECblGkUISvJSj58M1Kmn5HvA+9wSViyyzwIxcDYsLqHAT8pMs5qnHmR6hSu/zB11QG4AwoQXaQ8lZBQ0bROP+M/dFpwC1clFRXKpA/0ZmIqBbm6T3nNcEcw7QfZo9/CbV5EPgophBQdx1bQTsxs2Bv4NmZZYz1HZwl4bD08pbwhJECEuXD+TiUR4P83oN+jIqhStSjg==
  template:
    data: null
    metadata:
      name: config-bundle-secret
      namespace: quay