kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
- ../../../../../../components/apps/sso/overlays/default

resources:
- keycloak-migration-sealed-secret.yaml
- sso-oauth-client.yaml