apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: home-banner
spec:
  text: "Cluster: local.home - testing"
  location: BannerTop
  color: '#fff'
  backgroundColor: '#0088ce'