apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-disallow-anyuid-scc
  annotations:
    policy.open-cluster-management.io/standards: NIST 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-disallow-anyuid-scc
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: low
          namespaceSelector:
            exclude: ["kube-*","openshift-*","default","open-cluster-management-*"]
            include: ["*"]
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: wgpolicyk8s.io/v1alpha2
                kind: PolicyReport
                results:
                  - policy: disallow-security-context-constraint-anyuid
                    result: fail