---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

resources:
- github.com/redhat-cop/gitops-catalog/openshift-data-foundation-operator/operator/base

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: registry.redhat.io/openshift4/ose-cli:latest
    target:
      kind: Job
      name: enable-odf-console-plugin
  - patch: |-
      - op: replace
        path: /spec/channel
        value: stable-4.15
    target:
      kind: Subscription
      name: odf-operator
  - path: patch-namespace-annotation.yaml