apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  name: gitops-argocd-extended-role
rules:
  - apiGroups:
    - bitnami.com
    resources:
      - sealedsecrets
    verbs:
      - '*'
  - apiGroups:
    - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - '*'