apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: htpass-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgBWEOizznW3KiC0DrBe2164n6Z3L/yDLyEtqXFgNGp3DbYZdng8QnaDAM1cEZSKsT/rTMBl9T8LccOvuh8ug84XQYnhLfgaCkBhJmKqg5eRir2X8oe0YxIUjAjoTXtUwh0d72WCxM/vz9TsUqaF/ZRWOanxXo/kxqKaV6nT+HIJv52jiRMLWcDPaRmbZPIFYNotf1otytwargAMMBK6U6JvvOtBCPD/Qb4e0Alh8Oq+tv1lQDTuFx4QmZ3pGhJ9vuBhXkmanQErmQZImuWJytcJeMiUHzXqffE/rpjRUTCvUBvBWi20iEsSDRdCSbxQJS/yw4jcMegeg3fWUr8OP+jHfOBgX1hNlgsvd9LTC92FwGE0I42s9B8rjnZ58bZb/xHTAIFIM0+RRjOd+duNEGVom5TxpWn6Z193Q6mHY+QDiOXKWLE7fG3AtR2xz0rYa1SaawQZ27aP8Umbpv28YrxIzsaJtOZhye4OWYfVPAuk5BWfYOpFdKNL5UyvOaktABM8Vlme/9s+DKG+oOpZsflQQxjCVTwypd1HKxxdFbtjL9IeTVgvRPm3XrOFOcBCvBa/IxHkV0exUe6X7KreHIp7o5kvseuXMoQyDpZpZJg0CubSmUIcU8e82J5XIrcZ8cTRfxXlh7P8Xb4PA0E/OeM2D80WyhNIJlAR5hlSxDrydbRXPS9RrhyDHb1CsqTj8XKCxLPYZs3CUfu1NE8OaiAWNoHZ2tpkaKUL6v7mtAheI4dXI7RMr7UFe7a0wlyoeW7Zfhb9dVGkKqJYylafywaAXu8OXs0KTIquiE5f3QMlar3iXcYv3uX3oaoLHsDp0OXED9l9+i5R8G/0x2oVl0AzoDBW4E6tJSrWKXYjOQoMkePcZ2w+atGndmZ9snVpQvl3/JBmrcu4hogoYAV7OtYH5mJeIxcHjKeGOodFEpcVtXgH/xz2uNLB88U627xHVa5RNDVoAZvKNs1GG8EzBTFwFi4jYh3E7QAdCuPeKLOODUNvC89JUnasl0qSxhd64tGWx/REF90tph6BIYDTvjsOWYq6VGCIaFSNEZBupWHHbW7ISrIiRmuvMTDDs8f6mIKPM6GN+Ro9VXFhe9+fSq1H8QZYwhIYCx839qYbs4AH8efV
  template:
    metadata:
      name: htpass-secret
      namespace: openshift-config
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false