id: add-codeready-client
author: gnunn
realm: openshift
changes:
- addSimpleClient:
    clientId: codeready-public
    redirectUris:
    - "https://codeready-openshift-workspaces.apps.home.ocplab.com/_app/*"
    - "http://codeready-openshift-workspaces.apps.home.ocplab.com/_app/*"
    - "https://codeready-openshift-workspaces.apps.home.ocplab.com/workspace-loader/*"
    - "http://codeready-openshift-workspaces.apps.home.ocplab.com/swagger/*"
    - "https://codeready-openshift-workspaces.apps.home.ocplab.com/dashboard/*"
    - "http://codeready-openshift-workspaces.apps.home.ocplab.com/dashboard/*"
    - "http://codeready-openshift-workspaces.apps.home.ocplab.com/workspace-loader/*"
    - "https://codeready-openshift-workspaces.apps.home.ocplab.com/swagger/*"
    webOrigins:
    - "https://codeready-openshift-workspaces.apps.home.ocplab.com"
    - "http://codeready-openshift-workspaces.apps.home.ocplab.com"
- updateClient:
    clientId: codeready-public
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantEnabled: true