kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../../../components/apps/tenant-namespace/overlays/gitops
- ../../../defaults/networkpolicy/base
- product-catalog-admins-rolebinding.yaml
- product-catalog-users-rolebinding.yaml