apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: ocp4-cis-lab
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  extends: ocp4-cis
  description: Lab CIS profile
  title: Lab CIS profile
  disableRules:
  - name: ocp4-api-server-encryption-provider-cipher
    rationale: Using letsencrypt certificates, not applicable
  - name: ocp4-audit-log-forwarding-enabled
    rationale: Homelab so no log forwarding available
  - name: scc-limit-container-allowed-capabilities
    rationale: Some containers require extra privileges
  - name: configure-network-policies-namespaces
    rationale: Home lab supports ad-hoc demos