apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: ocp4-cis-lab
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"  
spec:
  extends: ocp4-cis
  description: NIST moderate profile
  title: My modified NIST moderate profile
  disableRules:
  - name: ocp4-cis-api-server-encryption-provider-cipher
    rationale: Using letsencrypt for certificates which does not set this
  - name: ocp4-cis-audit-log-forwarding-enabled
    rationale: Homelab so no log forwarding available
