apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: tenant
  version: 0.2.1
  repo: https://gnunn-gitops.github.io/helm-charts
  valuesFile: values.yaml
  namespace: gitops
  releaseName: product-catalog

resources:
- ./monitor
- groups.yaml
- github-pipeline-scc-rolebinding.yaml
