apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sensor-tls
  namespace: stackrox-secured-cluster-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: doppler-cluster
  target:
    name: sensor-tls
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: ACS_SENSOR_TLS