kind: SecuredCluster
apiVersion: platform.stackrox.io/v1alpha1
metadata:
  name: stackrox-secured-cluster-services
  namespace: stackrox-secured-cluster-service
spec:
  clusterName: dummy
  centralEndpoint: central-stackrox.apps.hub.ocplab.com:443