apiVersion: redhatcop.redhat.io/v1alpha1
kind: JWTOIDCAuthEngineConfig
metadata:
  name: keycloak
spec:
  authentication: 
    path: hub
    role: vault-admin
  path: keycloak
  OIDCClientID: "vault"
  OIDCCredentials:
    secret: 
      name: keycloak-client-secret-vault
    usernameKey: CLIENT_ID
    passwordKey: CLIENT_SECRET
  #OIDCDiscoveryURL: https://sso.${SUB_DOMAIN}/auth/realms/myorg
  OIDCDiscoveryURL: https://keycloak-sso.${SUB_DOMAIN}/auth/realms/myorg
  OIDCDiscoveryCAPEM: |
    -----BEGIN CERTIFICATE-----
    MIIDXzCCAkegAwIBAgIIAnTff7yGfxswDQYJKoZIhvcNAQELBQAwJjEkMCIGA1UE
    AwwbaW5ncmVzcy1vcGVyYXRvckAxNzE0MTk4ODMwMB4XDTI0MDQyNzA2MjE0N1oX
    DTI2MDQyNzA2MjE0OFowHzEdMBsGA1UEAwwUKi5hcHBzLmh1Yi5sYWIubG9jYWww
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDAhTuF2aQyYWjZkSUG3Lvn
    F0gkAzRJuCEskYZbWI3S1rop4PDnyTZ0PyKXiujnsVQNb1/S35QIvPOQJOdY+zDm
    uPOzl+TGN7XSAIq/PZoCr2BnqD3touXllN5tNw8nMmmG7A0VhBrsm2ewVhRHYV6Y
    jwb79/jgHrM5HlJYCbvnxfMexZAVa527kikJNlCTwE5U0kfCqD9QdeQ0iyQXXg+R
    BRSh52bACmFQHpY0ytjZcTL8f4mSsEi3LH/hJwOyK5bD11El/KZD2pS1vQ8cZnDi
    4LmMkGc1Lf/HM01lJfsCYbNzuLubCPw/rikqzKB7sKsMocfKv+0/7E57tfgcRNAz
    AgMBAAGjgZcwgZQwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMB
    MAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFG+JX58sHqMlguKhx0sXk+u9rpCdMB8G
    A1UdIwQYMBaAFCWgSVzxD8E0pXLqxcHn+SOqYRPfMB8GA1UdEQQYMBaCFCouYXBw
    cy5odWIubGFiLmxvY2FsMA0GCSqGSIb3DQEBCwUAA4IBAQB6bQky+I1aPFDU71/Q
    edWhi9MkeMW2wk3eL99zazMwL7EpWSiqygMjf3AgKMAZEMFrLxs/ee+NaqXtoYCp
    eKATKlXRJlmGW2s8U37DlBKj4rmzDCKYW6Rz+rxJ+OQjR/UNc2N4v/uMiVo+PDny
    VCqIvGY9hs8+XPVXRYPb00CMUDV/Y48mTfCaGpmx60eTBVSPJEJD/ba2QTY/1qAL
    K8wCaVrY7Fcmv5H9nIy46y90ozFFifXjbQ48UfGrEWMSo7D3TK0mDVtZK4RrfwIL
    AqikKi2Xm6oc8uBVUpWC1CrjkQ83RSwf8C6eO5FZUg53F06TaOW0yUFif3IustjN
    CySu
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDDDCCAfSgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtpbmdy
    ZXNzLW9wZXJhdG9yQDE3MTQxOTg4MzAwHhcNMjQwNDI3MDYyMDI5WhcNMjYwNDI3
    MDYyMDMwWjAmMSQwIgYDVQQDDBtpbmdyZXNzLW9wZXJhdG9yQDE3MTQxOTg4MzAw
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC3u6YUMKsrKpPeMGaCWAjU
    fKTA476amPh8vafW7ozymn0bN2oEFN4YyhEsjm5/pCdFoBH6ueqirZxgdIOJDQNu
    DvQ2Mo3yiUDT2czRtfiBl1elPxJOUJQzCiS9o71rO0Rk/a3DIvIka+ijgHDD2pN2
    ryBpgUQv0ecq17FzpDgXAjkTR1UGo1a9bMFfRnBLJdbf01WpEXRyg92+DUQbuLCp
    rKAeGjrWHCMxVCwwikjelUAR8hk+iRhi4Ezhu3I5nTewQu43H0zOvNfuZI9kV3FV
    mA+707rAciYh/VjUOqiZvdlIhLcx7Jplhw+J+moebV0Bmizev0WpY7kdWtGTQaWV
    AgMBAAGjRTBDMA4GA1UdDwEB/wQEAwICpDASBgNVHRMBAf8ECDAGAQH/AgEAMB0G
    A1UdDgQWBBQloElc8Q/BNKVy6sXB5/kjqmET3zANBgkqhkiG9w0BAQsFAAOCAQEA
    XENu/DKsek8ZiFVR99s8uo5EExJzRwqAf6Qm8cl/884Ups0Enyu5LvO88zUyzxbd
    BSgebCa3Q9hSNiWngCXrTA8IlwgFR1+tWfD9+pPLMr0b0gSCfnJDHHyYIY0Dc33F
    68caQRhJSTLYUz2l1ZXw8ydsTd+RNVLhvRu21ocvxzgkQDQHF2IvN61uDzeB8jFD
    EYIqdSVa+Jif43v1HqQmeH3FahN3RpqZ0qi1FF60ylEyugiiHfXGUMz9aWd7m38R
    bzMigSqpNr8Iye00ltWRHlnOY6u8QMu4rZKnsluSi4jy/MxYnQTC9QtrkcO5rUW6
    bnUS+lD0yEHO875j4LUnng==
    -----END CERTIFICATE-----
