apiVersion: redhatcop.redhat.io/v1alpha1
kind: PKISecretEngineConfig
metadata:
  name: intermediate
  namespace: vault-admin
spec:
  authentication: 
    path: hub
    role: vault-admin
    serviceAccount:
      name: default
  path: pki/intermediate
  commonName: vault.${SUB_DOMAIN}
  TTL: "8760h"
  type: intermediate
  privateKeyType: exported
  country: CN
  province: ZH
  locality: Zurich
  organization: Red Hat
  maxPathLength: 1
  issuingCertificates:
  - https://vault.${SUB_DOMAIN}/v1/pki/intermediate/ca
  externalSignSecret:
    name: signed-intermediate