apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: google-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgCL/OC1LiWNWGsiaXp4xfeC2Bqx17huAxG7vDGMptFw43BLa8ONSTXYxOHC0kpo4hRBggoKSMOz9HfRZNjtj3TK7HK3sPllvQKKAhGyjXdJ+BNqlrxYOc4cNOMjcJQKi/gRGw38bViA/fOFXBqETlTdyfTotUC9sHCmtmqwMcsZzYXOOlTw73sxVfpRgA6Ud8KtBUS8ZjEonJPulwf0GdWtbVtVj09sNbosuTWlpEw7arrRwlIsDrgkwiTWxnhLEc+XnR13ync8IJWMZCiDedrT+fSkRfvu3J2kmxYytRm8/cVh5U/VXhq5zRhWxyA97coa1vNHkgkQ7RZRbCUp2eGSB7J77Ecbg3Q1Bl05Z4CijxcZB4KSvQuVqKx0crp1OBOtpNN3cen0AUmqx0YEvOi2FjRt3+L6ZKjN8GL5lyYhaWKPlHATctsN3z5QKB4blwhAX3DDKFRQbOvJKH9tXDVUiSVAxYmKwdvcASnRDC8u22Ie7XF4ahNAc5tgtyvAaHOlMzYnhhewIVGH8brHr4tL+0br6IuX6Wfxv1kvBUh9bmrG9zYtBHEIaLqy+b1575aXsIEh1VAOwt9c5NqjCzoOSM2JGuLW6IxZkfblS+BODftlbRbwpneAp00ynOBWr6LsVWkSw5LZKM9FsecJnHtMjzw/Ny0YE1KXEWVJx1zIisaF+aSSbxjXVRGAnupHUvLUslhmr7grahqxzJlh8wjHAN7LSLF+D2E=
  template:
    metadata:
      name: google-secret
      namespace: openshift-config
    type: Opaque
