apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog-gitops

commonLabels:
  argocd.argoproj.io/instance: openshift-gitops

resources:
- ../../base
- ../../../../../components/apps/gitops-operator/base
- gitops-namespace.yaml
- operatorgroup.yaml
- product-catalog-project.yaml
- console-link.yaml

patches:
# Patch in namespace for Argo CD that is managing this namespace
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: product-catalog-gitops
  target:
    kind: RoleBinding
    name: gitops-argocd-extended-rolebinding
# Update permissions for instance
-  target:
     kind: ArgoCD
     name: argocd
   patch: |-
    - op: replace
      path: /spec/applicationInstanceLabelKey
      value: argocd.argoproj.io/product-catalog-instance
    - op: add
      path: /spec/rbac
      value:
        defaultPolicy: role:readonly
        policy: |
          g, product-catalog-admins, role:admin
          g, system:cluster-admins, role:admin
        scopes: "[groups]"