apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog-gitops

resources:
- ../../base
- ../../../../../components/apps/gitops-operator/base
- gitops-namespace.yaml
- operatorgroup.yaml
- product-catalog-project.yaml
- console-link.yaml

# Patch in namespace for Argo CD that is managing this namespace
patches:
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: product-catalog-gitops
  target:
    kind: ClusterRoleBinding
    name: gitops-argocd-extended-rolebinding