apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  size: 1x.extra-small
  storage:
    secret:
      name: loki-storage
      type: s3
  storageClassName: odf-lvm-vg
  tenants:
    mode: openshift-logging
