apiVersion: loki.grafana.com/v1beta1
kind: LokiStack
metadata:
  name: lokistack
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  size: 1x.extra-small
  storage:
    secret:
      name: loki-storage
      type: s3
  storageClassName: csi-driver-lvm-linear
  tenants:
    mode: openshift-logging
