apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-config

secretGenerator:
- name: matrix-login-template
  options:
    disableNameSuffixHash: true
  files:
    - login/matrix-login-template.html
- name: matrix-providers-template
  options:
    disableNameSuffixHash: true
  files:
    - login/matrix-providers-template.html    