apiVersion: operator.tekton.dev/v1alpha1
kind: TektonHub
metadata:
  name: hub
spec:
  targetNamespace: openshift-pipelines

  catalogs:
    - name: local
      org: AplphaGO
      type: community
      provider: github
      url: https://github.com/AplphaGO/tekton-tasks
      revision: main

  api:
    catalogRefreshInterval: 5m
