apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sso

# Used to generate an initial secret that we can then create the seal secret out of
# Note I left this here as an example, however each cluster will typically have their
# own sealed secret since some items such as IdPs or clients require cluster specific
# asettings.

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: keycloak-migration
  files:
  - secrets/keycloak-changelog.yml
  - secrets/01-realms.yml
  - secrets/02-clients-private.yml
  # - secrets/03-openshift-users-private.yml
  # - secrets/04-google-idp-private.yml

bases:
- github.com/redhat-canada-gitops/catalog/rhsso/rhsso-standalone/overlays/default

resources:
- keycloak-migration-job.yaml