apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-product-catalog
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: product-catalog-namespaces
            path: tenants/product-catalog/namespaces/base
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: product-catalog-gitops
            path: tenants/product-catalog/gitops-operator/overlays/default
      # template:
      #   metadata:
      #     name: '{{values.name}}'
      #   spec:
      #     destination: {}
      #     source:
      #       repoURL: https://github.com/gnunn-gitops/cluster-config
      #       targetRevision: master
      #       path: '{{values.path}}'
  template:
    metadata:
      name: '{{values.name}}'
    spec:
      project: tenant-product-catalog
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/gnunn-gitops/cluster-config
        targetRevision: master
        path: '{{values.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops