apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-product-catalog
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  generators:
    - list:
        elements:
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: dev
            path: tenants/product-catalog/namespaces/overlays/dev
            namespace: product-catalog-dev
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: test
            path: tenants/product-catalog/namespaces/overlays/test
            namespace: product-catalog-test
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: prod
            path: tenants/product-catalog/namespaces/overlays/prod
            namespace: product-catalog-prod
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: cicd
            path: tenants/product-catalog/namespaces/overlays/cicd
            namespace: product-catalog-cicd
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: monitor
            path: tenants/product-catalog/namespaces/overlays/monitor
            namespace: product-catalog-monitor
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: gitops
            path: tenants/product-catalog/namespaces/overlays/gitops
            namespace: product-catalog-gitops
        - cluster: local
          url: https://kubernetes.default.svc
          values:
            name: rbac
            path: tenants/product-catalog/rbac/base
  template:
    metadata:
      name: 'tenant-product-catalog-{{values.name}}'
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
    spec:
      project: tenants
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      source:
        repoURL: https://github.com/gnunn-gitops/cluster-config
        targetRevision: main
        path: '{{values.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{values.namespace}}'