apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: letsencrypt-aws
  namespace: openshift-operators
spec:
  encryptedData:
    secret-access-key: AgCDUZV++wWDRSPnPWeKPkfDnBLvZ/Ra6xvb0EInf56aSkLyG2/PbMFBi/Ja6O/tpR53QeHvNka7f7AXT87BfESVq6LuwB18I4J73TJ125yaSegKRIhU0KA8xXjB7BnJVmAGMb8WS27UeOOg40cBJJPPuTmmF3Hu/PYzPIezXTd43JPkofhe12NLUwfKGT30IF+qg5zX+6tFpgl28iKLORvfVPJdw0ObYNrFdFHgoBv5uKJcdV23J3fl2WLvHwMGmgA4pdouklSsEaaoeVjR8iCAOgY7L/XNpJ62jKkHXTMmPci4EOqHmT9R3uyhAxna82Qxv5w1vhujn8FvCHOmAMIqQbrcN9k7fx2rQEiuHIv3KjjE3xgNfhaP3zZrAKeVxKnm7skYUedBUVGku6LfVrkQsf7jBtCGIBZNoGwXfr5HGyTwaFAsHlevVBJpYhAIEaEtzULhzy6ZPYL9k4GzNHVEXpP5LNSpQvykpUt3MFUGQ2+S6nXQ2ET91S2yyu1kbLAlqlVScCX6kgUohDaQcjWJWUYFY1TOCVDM3kCeqSLTyQOoioChU0t5rwUhnpbE4wk04CSPsxuxgFuCFsUnRNapmyOa/rPuNH/YcjkR5RMZ6BLea3bDoP6eERsReME244UIMe3ORKlMGbPg1I/PP/IvnNFGXuZEOHLvU3YrxLo30A03FqlfoihsPqIvf80/xc50q9/F+VTMBfccCylcaDLq9ZxYWsYeig6AVEEC2VC2H+1VWD73atKI
  template:
    metadata:
      creationTimestamp: null
      name: letsencrypt-aws
      namespace: openshift-operators
    type: Opaque