- op: add
  path: /spec/identityProviders/1
  value:
  - name: Internal-SSO
    mappingMethod: claim
    type: OpenID
    openID:
      clientID: openshift
      clientSecret:
        name: openid-client-secret
      ca:
        name: openidcacrt
      extraScopes:
      - email
      - profile
      extraAuthorizeParameters:
        include_granted_scopes: "true"
      claims:
        preferredUsername:
        - preferred_username
        - email
        name:
        - nickname
        - given_name
        - name
        email:
        - custom_email_claim
        - email
      issuer: https://sso-sso.apps.home.ocplab.com/auth/realms/openshift