resources:
- ../../../../../../components/apps/certificates/base

patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - api.cluster.ocplab.com
    target:
      kind: Certificate
      name: openshift-api
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - '*.apps.cluster.ocplab.com'
      - op: replace
        path: /spec/commonName
        value: '*.apps.cluster.ocplab.com'
    target:
      kind: Certificate
      name: openshift-wildcard
