apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: kyverno-bestpractices
placementBindingDefaults:
  name: kyverno-bestpractices
policyDefaults:
  policyAnnotations: {"policy.open-cluster-management.io/disable-templates": "true"}
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: kyverno-policies
  remediationAction: enforce
  severity: medium
  policySets:
    - kyverno-best-practices
  standards:
    - generic
  generatePlacementWhenInSet: false
policies:
- name: policy-require-pod-probes
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: policies/validate-probes-policy.yaml
- name: require-requests-limits
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: policies/require-requests-limits-policy.yaml
policySets:
  - description: Kyverno Best Practices
    name: kyverno-best-practices
    placement:
      placementRuleName: kyverno