apiVersion: batch/v1
kind: Job
metadata:
  name: create-pipeline-local-user
  annotations:
    # argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - image: registry.redhat.io/openshift-gitops-1/argocd-rhel8:v1.4.2
        command:
          - /bin/bash
          - -c
          - |
            echo "Checking if pipeline account already there..."
            HAS_ACCOUNT=$(kubectl get cm argocd-cm -o jsonpath={.data."accounts\.pipeline"})
            if [ -z $HAS_ACCOUNT ];
            then
                echo "Pipeline account doesn't exist, adding"
                echo "Getting argocd admin credential..."
                if kubectl get secret argocd-cluster;
                then
                # Create pipeline user
                kubectl patch cm argocd-cm --patch '{"data": {"accounts.pipeline": "apiKey"}}'
                # Update password
                PASSWORD=$(oc get secret argocd-cluster -o jsonpath="{.data.admin\.password}" | base64 -d)
                argocd login --username admin --password ${PASSWORD} ${ARGOCD_HOST}
                TOKEN=$(argocd account generate-token --account pipeline)
                kubectl create secret generic argocd-api-token --from-literal=token=${TOKEN} -n ${CICD_NAMESPACE}
                else
                echo "Secret argocd-cluster not available, could not interact with API"
                fi
            else
                echo "Pipeline account already added, skipping"
            fi
        env:
        # The ARGO CD host to connect to
        - name: ARGOCD_HOST
          value: ""
        # The CICD namespace where the token needs to be deployed to
        - name: CICD_NAMESPACE
          value: ""
        imagePullPolicy: Always
        name: create-pipeline-local-user
      serviceAccount: argocd-argocd-application-controller
      serviceAccountName: argocd-argocd-application-controller
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30