apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gitops-operator-cr.yaml
- gitops-workaround-993-role.yaml
- in-cluster-secret.yaml
# - patch-cluster-namespaces-rbac.yaml
# - patch-cluster-namespaces-job.yaml