apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: rox-image-scan
  namespace: pipeline-demo
spec:
  params:
    - name: image
      type: string
      description: Full name of image to scan (example -- gcr.io/rox/sample:5.0-rc1)
    - name: output_format
      type: string
      description:  Output format (json | csv )
      default: json
  workspaces:
    - name: acs-central
      description: The secret with the central endpoint (rox-central_endpoint) and api token (rox_api_token)
      optional: true
  steps:
    - name: rox-image-scan
      image: centos:8
      script: |
        #!/usr/bin/env bash
        set +x

        if [ $(workspaces.acs-central.bound) == "false" ] ; then
          echo "No acs-central workspace was bound to task"
          exit 0
        fi

        export ROX_CENTRAL_ENDPOINT=$(cat $(workspaces.acs-central.path)/rox_central_endpoint)
        export ROX_API_TOKEN=$(cat $(workspaces.acs-central.path)/rox_api_token)

        echo "Scanning against endpoint ${ROX_CENTRAL_ENDPOINT}"

        export NO_COLOR="True"
        curl -k -L -H "Authorization: Bearer $ROX_API_TOKEN" https://$ROX_CENTRAL_ENDPOINT/api/cli/download/roxctl-linux --output ./roxctl  > /dev/null; echo "Getting roxctl"
        chmod +x ./roxctl > /dev/null

        echo "Scanning image: $(params.image)"

        ./roxctl image scan --insecure-skip-tls-verify -e $ROX_CENTRAL_ENDPOINT --image $(params.image) --format $(params.output_format)