apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: sso-account
spec:
  href: 'https://keycloak-sso.apps.hub.lab.local/auth/realms/myorg/account'
  location: UserMenu
  text: Account Settings
