apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-cert-manager-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: openshift-cert-manager-operator
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: components/apps/cert-manager-operator/overlays/letsencrypt
    repoURL: https://github.com/gnunn-gitops/cluster-config.git
    targetRevision: main
  syncPolicy:
    automated: {}