apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sc.yaml
- pv.yaml

# patches:
#   - target:
#       kind: PersistentVolume
#     patch: |-
#       - op: replace
#         path: /spec/persistentVolumeReclaimPolicy
#         value: Recycle