apiVersion: operator.openshift.io/v1
kind: KubeDescheduler
metadata:
  name: cluster
  namespace: openshift-kube-descheduler-operator
spec:
  logLevel: Normal
  mode: Automatic
  operatorLogLevel: Normal
  profileCustomizations:
    devLowNodeUtilizationThresholds: Medium
  profiles:
    - LifecycleAndUtilization
  deschedulingIntervalSeconds: 900
  managementState: Managed
