apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ACM Configuration Policies
    openshift.io/display-name:  ACM Configuration Policies
  name: open-cluster-management-config-policies