apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openshift-api
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  secretName: openshift-api-certificate
  issuerRef:
    name: vault-service
    kind: ClusterIssuer
  dnsNames:
  - replace.me
