apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openshift-wildcard
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  duration: 1h
  renewBefore: 55m  
  secretName: openshift-wildcard-certificate
  issuerRef:
    name: vault-service
    kind: ClusterIssuer
  commonName: '*.apps.replace.me'
  dnsNames:
  - '*.apps.replace.me'
