apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: hub-server
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  desiredState:
    interfaces:
    - name: enp0s31f6
      state: absent
      type: ethernet
      ipv4:
        dhcp: true
        enabled: true
        auto-dns: true