apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: hub-server
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  desiredState:
    interfaces:
    # - name: enp4s0
    #   state: up
    #   type: ethernet
    #   ipv4:
    #     dhcp: true
    #     enabled: true
    #     auto-dns: true
    - name: enp0s31f6
      state: absent
      type: ethernet
      ipv4:
        dhcp: true
        enabled: true
        auto-dns: true
    # routes:
    #   config:
    #     - destination: 0.0.0.0/0
    #       next-hop-address: 192.168.1.1
    #       next-hop-interface: enp4s0
    #       table-id: 254